apiVersion: v1
kind: Pod
metadata:
  name: netflix-app
  labels:
    app: netflix
spec:
  containers:
  - name: netflix-app-container
    image: devopsinsiders/netflix-clone
    ports:
    - containerPort: 80
---
    apiVersion: v1
    kind: Pod
    metadata:
      name: photo-app
      labels:
        app: netflix
    spec:
      containers:
      - name: photo-app-container
        image: ershad150/photo-apps
        ports:
        - containerPort: 80

